#Location to teleport, default: 0.0, 100.0, 0.0
location:
  x: 0.0
  y: 100.0
  z: 0.0

#View direction after teleport, default: 0.0, 0.0
direction:
  yaw: 0.0
  pitch: 0

#World to teleport, default: world
world: world